// <auto-generated />
using BBSolarOMS.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;

namespace BBSolarOMS.Migrations
{
    [DbContext(typeof(BBSolarOMSContext))]
    [Migration("20180622150721_AddLocation")]
    partial class AddLocation
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.3-rtm-10026")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BBSolarOMS.Entities.Distributor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ActiveMail")
                        .IsRequired();

                    b.Property<string>("ActiveMobileNumber")
                        .IsRequired();

                    b.Property<string>("CoperateName")
                        .HasMaxLength(55);

                    b.Property<DateTimeOffset>("DateCreated");

                    b.Property<string>("FirstName")
                        .HasMaxLength(25);

                    b.Property<string>("LGA")
                        .IsRequired();

                    b.Property<DateTimeOffset>("LastEditedOn");

                    b.Property<string>("LastName")
                        .HasMaxLength(25);

                    b.Property<string>("ResidentialProvinceAddress")
                        .IsRequired();

                    b.Property<string>("State")
                        .IsRequired();

                    b.HasKey("Id");

                    b.ToTable("Distributors");
                });

            modelBuilder.Entity("BBSolarOMS.Entities.Installers", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Address")
                        .IsRequired();

                    b.Property<DateTimeOffset>("DOB");

                    b.Property<DateTimeOffset>("DateCreated");

                    b.Property<string>("Email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("Gender");

                    b.Property<string>("LGA");

                    b.Property<DateTimeOffset>("LastEditedOn");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(25);

                    b.Property<string>("MobileNumber")
                        .IsRequired();

                    b.Property<string>("State");

                    b.HasKey("Id");

                    b.ToTable("Installers");
                });
#pragma warning restore 612, 618
        }
    }
}
